---

- name: Update taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_taps }}"
  when: (brew_taps and ansible_os_family == "Darwin")

- name: Brew formulas 
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_formulas }}"
  when: (brew_formulas and ansible_os_family == "Darwin")

- name: Brew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_casks }}"
  when: (brew_casks and ansible_os_family == "Darwin")

