---

brew_install: false
brew_configure: false

brew_taps:
  - homebrew/dupes

brew_formulas:
  - git
  - terraform
  - vim
  - bash
  - coreutils
  - autoenv
  - openssl
  - lastpass-cli

brew_casks:
  - google-chrome
  - slack
  - virtualbox
  - vagrant  
  - karabiner-elements
  - atom


